import Vue from 'vue';
import Vuex from 'vuex';

Vue.use(Vuex);

export default new Vuex.Store({
  state: {
    tituloApp: 'Trade Center',
    carrinho: [
      {
        id: 'moletom-ninja-1',
        nome: 'Moletom Ninja',
        preco: '299.99',
        descricao: 'Esse é um novo Moletom.',
        estoque: 10,
        fotos: [
          'http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/hoodie_5_front.jpg',
          'http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/hoodie_5_back.jpg',
        ],
        categorias: ['masculino', 'feminino', 'moletom'],
        peso_kg: 0.8,
        altura_cm: 100,
        largura_cm: 70,
        comprimento_cm: 5,
        promocao: false,
        preco_promocao: '',
        publicado: true,
      },
      {
        id: 'moletom-ninja-2',
        nome: 'Moletom Ninja',
        preco: '299.99',
        descricao: 'Esse é um novo Moletom.',
        estoque: 10,
        fotos: [
          'http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/hoodie_5_front.jpg',
          'http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/hoodie_5_back.jpg',
        ],
        categorias: ['masculino', 'feminino', 'moletom'],
        peso_kg: 0.8,
        altura_cm: 100,
        largura_cm: 70,
        comprimento_cm: 5,
        promocao: false,
        preco_promocao: '',
        publicado: true,
      },
      {
        id: 'moletom-ninja-3',
        nome: 'Moletom Ninja',
        preco: '299.99',
        descricao: 'Esse é um novo Moletom.',
        estoque: 10,
        fotos: [
          'http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/hoodie_5_front.jpg',
          'http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/hoodie_5_back.jpg',
        ],
        categorias: ['masculino', 'feminino', 'moletom'],
        peso_kg: 0.8,
        altura_cm: 100,
        largura_cm: 70,
        comprimento_cm: 5,
        promocao: false,
        preco_promocao: '',
        publicado: true,
      },
      {
        id: 'moletom-ninja-4',
        nome: 'Moletom Ninja',
        preco: '299.99',
        descricao: 'Esse é um novo Moletom.',
        estoque: 10,
        fotos: [
          'http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/hoodie_5_front.jpg',
          'http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/hoodie_5_back.jpg',
        ],
        categorias: ['masculino', 'feminino', 'moletom'],
        peso_kg: 0.8,
        altura_cm: 100,
        largura_cm: 70,
        comprimento_cm: 5,
        promocao: false,
        preco_promocao: '',
        publicado: true,
      },
      {
        id: 'moletom-ninja-5',
        nome: 'Moletom Ninja',
        preco: '299.99',
        descricao: 'Esse é um novo Moletom.',
        estoque: 10,
        fotos: [
          'http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/hoodie_5_front.jpg',
          'http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/hoodie_5_back.jpg',
        ],
        categorias: ['masculino', 'feminino', 'moletom'],
        peso_kg: 0.8,
        altura_cm: 100,
        largura_cm: 70,
        comprimento_cm: 5,
        promocao: false,
        preco_promocao: '',
        publicado: true,
      },
      {
        id: 'moletom-ninja-6',
        nome: 'Moletom Ninja',
        preco: '299.99',
        descricao: 'Esse é um novo Moletom.',
        estoque: 10,
        fotos: [
          'http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/hoodie_5_front.jpg',
          'http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/hoodie_5_back.jpg',
        ],
        categorias: ['masculino', 'feminino', 'moletom'],
        peso_kg: 0.8,
        altura_cm: 100,
        largura_cm: 70,
        comprimento_cm: 5,
        promocao: false,
        preco_promocao: '',
        publicado: true,
      },
      {
        id: 'moletom-ninja-7',
        nome: 'Moletom Ninja',
        preco: '299.99',
        descricao: 'Esse é um novo Moletom.',
        estoque: 10,
        fotos: [
          'http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/hoodie_5_front.jpg',
          'http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/hoodie_5_back.jpg',
        ],
        categorias: ['masculino', 'feminino', 'moletom'],
        peso_kg: 0.8,
        altura_cm: 100,
        largura_cm: 70,
        comprimento_cm: 5,
        promocao: false,
        preco_promocao: '',
        publicado: true,
      },
      {
        id: 'moletom-ninja-8',
        nome: 'Moletom Ninja',
        preco: '299.99',
        descricao: 'Esse é um novo Moletom.',
        estoque: 10,
        fotos: [
          'http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/hoodie_5_front.jpg',
          'http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/hoodie_5_back.jpg',
        ],
        categorias: ['masculino', 'feminino', 'moletom'],
        peso_kg: 0.8,
        altura_cm: 100,
        largura_cm: 70,
        comprimento_cm: 5,
        promocao: false,
        preco_promocao: '',
        publicado: true,
      },
    ],
    usuario: 'Entrar / Cadastrar',
    logado: false,
  },
  mutations: {
  },
  actions: {
  },
  modules: {
  },
});
